from typing import TypedDict, List, Annotated
import operator


class AgentState(TypedDict):
    # Using Annotated with operator.add ensures that messages 
    # are appended to the history rather than replaced.
    messages: Annotated[List[dict], operator.add]
    current_query: str      #query given by the user
    documents: List[str]    #list of relevant documents
    plan: List[str]         #plan of action for the agent - technical or conversational
    status: str             #on which node currently the agent is operating
    final_answer: str       #final answer generated by the agent after processing the query
